### ISSUE TITLE
Owa-epanet RequirementError

### ISSUE THREAD

**Issue by ludderi** [OpenWaterAnalytics/epanet-python#74]
I was following the building instructions in the readme at owa-epanet and when preforming `pipenv install ../dist /*.whl` I met the following error

```
C:\Users\lulin\pythonroom\epanet-python\owa-epanet\dist>pipenv install *whl    
Installing *whl...                                                                                                   
Traceback (most recent call last):                                                                                  
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 98, in __init__                                                                                   
           req = REQUIREMENT.parseString(requirement_string)                                                            
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1654, in parseString                                                                                             
           raise exc                                                                                                       
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1644, in parseString                                                             
           loc, tokens = self._parse( instring, 0 )                                                                     
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache                                                                         
           loc,tokens = self.parseImpl( instring, preloc, doActions )                                                   
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3417, in parseImpl                                                                           
           loc, exprtokens = e._parse( instring, loc, doActions )                                                        
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache                                                                                     
          loc,tokens = self.parseImpl( instring, preloc, doActions )                                                    
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3739, in parseImpl                                                                                       
           return self.expr._parse( instring, loc, doActions, callPreParse=False )                                       
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache                                                                                   
           loc,tokens = self.parseImpl( instring, preloc, doActions )                                                    
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3400, in parseImpl                                                                                       
           loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )                        
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1406, in _parseNoCache                                                                                   
           loc,tokens = self.parseImpl( instring, preloc, doActions )                                                    
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 2711, in parseImpl                                                                                       
           raise ParseException(instring, loc, self.errmsg, self)                                                           
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)                                                                                                                                         

During handling of the above exception, another exception occurred:                                                                                                                                                                       

Traceback (most recent call last):                                                                                
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 966, in _parse_name_from_line                                                          
           self._requirement = init_requirement(self.line)                                                               
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pipenv\vendor\requirementslib\models\utils.py", line 200, in init_requirement                                                                      
           req = Requirement.parse(name)                                                                                 
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 3139, in parse                                                                                                    
           req, = parse_requirements(s)                                                                                  
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 3084, in parse_requirements                                                                                       
           yield Requirement(line)                                                                                       
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 3094, in __init__                                                                                                 
           super(Requirement, self).__init__(requirement_string)                                                         
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 100, in __init__                                                                            
           raise InvalidRequirement(                                                                                        
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'*whl'": Expected W:(abcd...)                                                                                                                             

During handling of the above exception, another exception occurred:                                                                                                                                                                       

Traceback (most recent call last):                                                                                
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main 
           return _run_code(code, main_globals, None,                                                                   
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code            
           exec(code, run_globals)                                                                                       
     File "C:\Users\lulin\AppData\Local\Programs\Python\Python39\Scripts\pipenv.exe\__main__.py", line 7, in <module>
     File "C:\Users\lulin\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__                                                                                                
           return self.main(*args, **kwargs)                                                                             
     File "C:\Users\lulin\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 782, in main                                                                                                    
           rv = self.invoke(ctx)                                                                                         
     File "C:\Users\lulin\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 1259, in invoke                                                                                                 
           return _process_result(sub_ctx.command.invoke(sub_ctx))                                                       
     File "C:\Users\lulin\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke                                                                                                 
           return ctx.invoke(self.callback, **ctx.params)                                                               
     File "C:\Users\lulin\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke                                                                                                 
           return callback(*args, **kwargs)                                                                             
     File "C:\Users\lulin\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func                                                                                          
           return ctx.invoke(f, obj, *args, **kwargs)                                                                   
     File "C:\Users\lulin\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke                                                                                                  
           return callback(*args, **kwargs)                                                                              
     File "C:\Users\lulin\AppData\Local\Programs\Python\Python39\Lib\site-packages\pipenv\vendor\click\decorators.py", line 21, in new_func                                                                                           
           return f(get_current_context(), *args, **kwargs)                                                              
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pipenv\cli\command.py", line 233, in install                                                                                                       
           retcode = do_install(                                                                                         
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pipenv\core.py", line 2100, in do_install                                                                                                          
           pkg_requirement = Requirement.from_line(pkg_line)                                                             
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 2676, in from_line                                                                     
           parsed_line = Line(line)                                                                                      
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 171, in __init__                                                                       
           self.parse()                                                                                                  
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 1304, in parse                                                                         
           self.parse_name()                                                                                            
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 1027, in parse_name                                                                   
           name = self._parse_name_from_line()                                                                           
     File "c:\users\lulin\appdata\local\programs\python\python39\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 968, in _parse_name_from_line                                                          
           raise RequirementError(                                                                                          
pipenv.vendor.requirementslib.exceptions.RequirementError: Failed parsing requirement from '*whl'
```

I hope someone can provide some guidance in how to solve this error.

**Comment by samhatchett** [comment]
I think we'll need more info here - looks like python 3.9, using pipenv (what version?) - also seems strange to run pipenv commands from the `dist` directory. Also how was the wheel built, and were there any errors or problems during that phase?

might be easier to just install/build from pypi, as that has a proven track record.

**Comment by samhatchett** [comment]
closing due to lack of info and inactivity
